global upd

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -36,16 +36,16 @@ jobs:
           echo "DOCKER_TAG=${TAG}" >> $GITHUB_ENV
           echo "Docker tag set to ${TAG}"
 
-      # 3. Аутентификация в Docker Hub с использованием пароля
+      # 3. Аутентификация в Docker Hub
       - name: Log in to Docker Hub
         run: |
-          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "m0ln1z" --password-stdin
 
-      # 4. Сборка и пуш Docker-образа с указанным скриптом бота
+      # 4. Сборка и пуш Docker-образа
       - name: Build and push Docker image
         run: |
-          docker build --build-arg BOT_SCRIPT=${{ matrix.bot.bot_script }} -t "${{ matrix.bot.image }}:${{ env.DOCKER_TAG }}" .
-          docker push "${{ matrix.bot.image }}:${{ env.DOCKER_TAG }}"
+          docker build --build-arg BOT_SCRIPT=${{ matrix.bot.bot_script }} -t "m0ln1z/${{ matrix.bot.image }}:${{ env.DOCKER_TAG }}" .
+          docker push "m0ln1z/${{ matrix.bot.image }}:${{ env.DOCKER_TAG }}"
 
       # 5. Настройка SSH-агента для использования SSH-ключей
       - name: Setup SSH
@@ -76,13 +76,13 @@ jobs:
             fi
 
             # Логин в Docker Hub
-            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
+            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "m0ln1z" --password-stdin
 
             # Пулл обновлённого образа
-            docker pull ${{ matrix.bot.image }}:${{ env.DOCKER_TAG }}
+            docker pull m0ln1z/${{ matrix.bot.image }}:${{ env.DOCKER_TAG }}
 
             # Проверка успешного пулла
-            docker images | grep ${{ matrix.bot.image }}:${{ env.DOCKER_TAG }} && echo "Image pulled successfully." || { echo "Failed to pull image."; exit 1; }
+            docker images | grep "m0ln1z/${{ matrix.bot.image }}:${{ env.DOCKER_TAG }}" && echo "Image pulled successfully." || { echo "Failed to pull image."; exit 1; }
 
             # Остановка и удаление старого контейнера
             docker stop selenium-bot-${{ matrix.bot.name }} || docker kill selenium-bot-${{ matrix.bot.name }} || true
@@ -98,6 +98,6 @@ jobs:
               --shm-size=256m \
               -e BOT_TOKEN='${{ secrets[matrix.bot.bot_token_secret] }}' \
               -e CHAT_ID='${{ secrets[matrix.bot.chat_id_secret] }}' \
-              ${{ matrix.bot.image }}:${{ env.DOCKER_TAG }}
+              m0ln1z/${{ matrix.bot.image }}:${{ env.DOCKER_TAG }}
 
             echo "Deployment completed successfully."
